### PR TITLE
Use Youtube privacy-enhanced mode

### PR DESCRIPTION
**Pull request by tdelmas**
See "Turn on privacy-enhanced mode" on https://support.google.com/youtube/answer/171780?hl=en

IMPORTANT: do NOT merge this PR before adding in the CSP frame-src "https://www.youtube-nocookie.com" after "https://www.youtube.com" (by updating https://github.com/abetterinternet/website/blob/master/content/en/_headers accordingly?)

See also https://github.com/abetterinternet/website/pull/27 and https://github.com/letsencrypt/website/pull/468

@andygabby Side note: should/could the _headers mechanism be also applied to letsencrypt.org?

### CODE REVIEW

**Comment by tdelmas** [comment]
(@andygabby With this PR I discover netlify. I'm a fan, especially the tests rules and preview option. Would be useful for https://github.com/letsencrypt/website ...)

**Comment by andygabby** [comment]
> (@andygabby With this PR I discover netlify. I'm a fan, especially the tests rules and preview option. Would be useful for https://github.com/letsencrypt/website ...)

I am in process of migrating abetterinternet.org to Netlify. I plan to change DNS at the first of the week. The _headers file will auto update the CSP at Netflify but on the server where it currently is running, so probably best to hold off on the merge until after the migration is complete. 

> @andygabby Side note: should/could the _headers mechanism be also applied to letsencrypt.org?

After moving this site I will be moving letsencrypt.org there as well and we can use the _headers file and all the other Netlify goodness!

**Comment by andygabby** [comment]
@tdelmas, could you add the necessary changes to the to CSP in content/en/_headers to this PR so we can see what the test build looks like with it?

**Comment by tdelmas** [comment]
Sure, done!

**Pull request merged**
